apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-app-deploy"
  labels:
    app: mongo
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.deploy.image.repository }}:{{ .Chart.AppVersion }}"