apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-apps-svc"
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
